version: '3'
services:
    nginx:
      image: nginx:stable-alpine
      ports:
        - "4000:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        # ports:
        #     - '4000:4000'
        env_file:
            - ./.env
        depends_on:
          - mongo
    mongo:
        image: mongo
        volumes:
          - mongo-db:/data/db
    redis:
        image: redis
        volumes:
          - redis-db:/data/redis
volumes:
  mongo-db:
  redis-db:
